version: "3"
services:
    course-cli:
        image: dbwebb/courserepo:course-cli
        volumes:
            - .:/home/dbwebb/repo
        ports: [ "10042:80" ]
    cli: &cli
        image: dbwebb/courserepo:cli
        volumes:
            - ".:/home/dbwebb/repo"
            - "./example/sql/inspect/my.cnf:/home/dbwebb/.my.cnf"
    server:
        <<: *cli
        ports:
            - "1337:1337"
